Chunk ::= Block

Block ::= {Stat} [Retstat]

Stat ::=  ';' | 
        Varlist '=' Explist | 
        Functioncall | 
        Label | 
        'break' | 
        'goto' name | 
        'do' Block 'end' | 
        'while' Exp 'do' Block 'end' | 
        'repeat' Block 'until' Exp | 
        'if' Exp 'then' Block {'elseif' Exp 'then' Block} ['else' Block] 'end' | 
        'for' name '=' Exp ',' Exp [',' Exp] 'do' Block 'end' | 
        'for' Namelist 'in' Explist 'do' Block 'end' | 
        'function' funcname Funcbody | 
        'local' 'function' name Funcbody | 
        'local' Attnamelist ['=' Explist] 

Attnamelist ::=  name Attrib {',' name Attrib}

Attrib ::= ['<' name '>']

Retstat ::= 'return' [Explist] [';']

Label ::= '::' name '::'

funcname ::= name {'.' name} [':' name]

Varlist ::= Var {',' Var}

Var ::=  name | Prefixexp '[' Exp ']' | Prefixexp '.' name 

Namelist ::= name {',' name}

Explist ::= Exp {',' Exp}

Exp ::=  nil | false | true | numeral | literalString | '...' | Functiondef | 
        Prefixexp | Tableconstructor | Exp Binop Exp | Unop Exp 

Prefixexp ::= Var | Functioncall | '(' Exp ')'

Functioncall ::=  Prefixexp Args | Prefixexp ':' name Args 

Args ::=  '(' [Explist] ')' | Tableconstructor | literalString 

Functiondef ::= function Funcbody

Funcbody ::= '(' [Parlist] ')' Block end

Parlist ::= Namelist [',' '...'] | '...'

Tableconstructor ::= '{' [Fieldlist] '}'

Fieldlist ::= Field {Fieldsep Field} [Fieldsep]

Field ::= '[' Exp ']' '=' Exp | name '=' Exp | Exp

Fieldsep ::= ',' | ';'

Binop ::=  '+' | '-' | '*' | '/' | '//' | '^' | '%' | 
        '&' | '~' | '|' | '>>' | '<<' | '..' | 
        '<' | '<=' | '>' | '>=' | '==' | '~=' | 
        'and' | 'or'

Unop ::= '-' | 'not' | '#' | '~'