Chunk = Block.

Block = {Stat}, [Retstat].

Stat =  ';' | 
        Varlist, '=', Explist | 
        Functioncall | 
        Label | 
        'break' | 
        'goto', ident | 
        'do', Block, 'end' | 
        'while', Exp, 'do', Block, 'end' | 
        'repeat', Block, 'until', Exp | 
        'if', Exp, 'then', Block, {'elseif', Exp, 'then', Block}, ['else', Block], 'end' | 
        'for', ident, '=', Exp, ',', Exp, [',', Exp], 'do', Block, 'end' | 
        'for', Namelist, 'in', Explist, 'do', Block, 'end' | 
        'function', funcname, Funcbody | 
        'local', 'function', ident, Funcbody | 
        'local', Attnamelist, ['=', Explist].

Attnamelist = ident, Attrib, {',', ident, Attrib}.

Attrib = ['<', ident, '>'].

Retstat = 'return', [Explist], [';'].

Label = '::', ident, '::'.

funcname = ident, {'.' ,ident}, [':', ident].

Varlist = Var ,{',', Var}.

Var =  ident | Prefixexp, '[', Exp ,']' | Prefixexp, '.', ident .

Namelist = ident ,{',', ident}.

Explist = Exp, {',', Exp}.

Exp =  nil | false | true | numeral | literal_string | '...' | Functiondef | 
        Prefixexp | Tableconstructor | Exp ,Binop, Exp | Unop, Exp .

Prefixexp = Var | Functioncall | '(', Exp ,')'.

Functioncall =  Prefixexp, Args | Prefixexp ,':', ident, Args. 

Args =  '(' ,[Explist] ,')' | Tableconstructor | literal_string .

Functiondef = function , Funcbody.

Funcbody = '(' ,[Parlist], ')' ,Block, end.

Parlist = Namelist, [',', '...'] | '...'.

Tableconstructor = '{', [Fieldlist], '}'.

Fieldlist = Field, {Fieldsep, Field}, [Fieldsep].

Field = '[' ,Exp ,']', '=' ,Exp | ident ,'=', Exp | Exp.

Fieldsep = ',' | ';'.

Binop =  '+' | '-' | '*' | '/' | '//' | '^' | '%' | 
        '&' | '~' | '|' | '>>' | '<<' | '..' | 
        '<' | '<=' | '>' | '>=' | '==' | '~=' | 
        'and' | 'or'.

Unop = '-' | 'not' | '#' | '~'.