Chunk ::= Block

Block ::= { Stat } [ "return" [ ExpList ] [ ";" ] ]

Stat ::=  ";" | 
     VarList "=" ExpList | 
     FunctionCall | 
     "::" ident "::" | 
     "break" | 
     "goto" ident | 
     "do" Block "end" | 
     "while" Exp "do" Block "end" | 
     "repeat" Block "until" Exp | 
     "if" Exp "then" Block { "elseif" Exp "then" Block } [ "else" Block] "end" | 
     "for" ident "=" Exp "," Exp [ "," Exp ] "do" Block "end" |
     "for" NameList "in" ExpList "do" Block "end" |
     "function" FuncName FuncBody | 
     "local" "function" ident FuncBody |
     "local" AttNameList [ "=" ExpList ]

AttNameList ::=  ident Attrib {"," ident Attrib}

Attrib ::= [ "<" ident ">" ]

FuncName ::= ident {"." ident} [":" ident]

VarList ::= Var {"," Var}

#Var ::=  ident | PrefixExp ("[" Exp "]" | "." ident)
Var ::=  ident | (Var | FunctionCall | "(" Exp ")") ("[" Exp "]" | "." ident)
Var ::=  ident | ((Var | FunctionCall | "(" Exp ")") "[" Exp "]" | (Var | FunctionCall | "(" Exp ")") "." ident)
Var ::=  ident | (Var | FunctionCall | "(" Exp ")") "[" Exp "]" | (Var | FunctionCall | "(" Exp ")") "." ident
Var ::=  ident | Var "[" Exp "]" | FunctionCall "[" Exp "]" | "(" Exp ")" "[" Exp "]" | Var "." ident | FunctionCall "." ident | "(" Exp ")" "." ident
Var ::=  ident | Var ("[" Exp "]" | "." ident) | FunctionCall ("[" Exp "]"  | "." ident) | "(" Exp ")" ("[" Exp "]"  | "." ident)
Var ::=  ident | FunctionCall ("[" Exp "]"  | "." ident) | "(" Exp ")" ("[" Exp "]"  | "." ident)

NameList ::= ident {"," ident}

ExpList ::= Exp {"," Exp}

Exp ::=  "nil" | "false" | "true" | numeral | literal_string | "..." | FunctionDef |
     PrefixExp | TableConstructor | Exp BinOp Exp | UnOp Exp 

PrefixExp ::= Var {("[" Exp "]" | "." ident)} | FunctionCall | "(" Exp ")"
PrefixExp ::= (ident | FunctionCall ("[" Exp "]"  | "." ident) | "(" Exp ")" ("[" Exp "]"  | "." ident)) {("[" Exp "]" | "." ident)} | FunctionCall | "(" Exp ")"
PrefixExp ::= (ident | "(" Exp ")" ("[" Exp "]"  | "." ident) | FunctionCall ("[" Exp "]"  | "." ident)) {("[" Exp "]" | "." ident)} | FunctionCall | "(" Exp ")"
PrefixExp ::= (ident | "(" Exp ")" ("[" Exp "]"  | "." ident)) {("[" Exp "]" | "." ident)} | FunctionCall {("[" Exp "]" | "." ident)} | "(" Exp ")"
PrefixExp ::= (ident | "(" Exp ")" ("[" Exp "]"  | "." ident) | FunctionCall) {("[" Exp "]" | "." ident)} | "(" Exp ")"
PrefixExp ::= "(" Exp ")" | (ident | "(" Exp ")" ("[" Exp "]"  | "." ident) | FunctionCall) {("[" Exp "]" | "." ident)}
PrefixExp ::= "(" Exp ")"   |   ident {("[" Exp "]" | "." ident)}   |   "(" Exp ")" ("[" Exp "]"  | "." ident) {("[" Exp "]" | "." ident)}   |   FunctionCall {("[" Exp "]" | "." ident)}
PrefixExp ::= "(" Exp ")"   |   "(" Exp ")" ("[" Exp "]" | "." ident) {("[" Exp "]" | "." ident)}   |   ident {("[" Exp "]" | "." ident)}   |   FunctionCall {("[" Exp "]" | "." ident)}

#PrefixExp ::= "(" Exp ")" [("[" Exp "]"  | "." ident) {("[" Exp "]" | "." ident)}]   |   ident {("[" Exp "]" | "." ident)}   |   FunctionCall {("[" Exp "]" | "." ident)}
#PrefixExp ::= "(" Exp ")"   |   ("(" Exp ")" ("[" Exp "]"  | "." ident) | ident | FunctionCall) {("[" Exp "]" | "." ident)}
PrefixExp ::= PrefixExp [":" ident] Args {("[" Exp "]" | "." ident)}   |   "(" Exp ")"   |   "(" Exp ")" ("[" Exp "]" | "." ident) {("[" Exp "]" | "." ident)}   |   ident {("[" Exp "]" | "." ident)}   
PrefixExp ::= ("(" Exp ")"   |   "(" Exp ")" ("[" Exp "]" | "." ident) {("[" Exp "]" | "." ident)}   |   ident {("[" Exp "]" | "." ident)}) {[":" ident] Args {("[" Exp "]" | "." ident)}}

FunctionCall ::=  PrefixExp [":" ident] Args 

Args ::=  "(" [ExpList] ")" | TableConstructor | literal_string

FunctionDef ::= "function" FuncBody

FuncBody ::= "(" [ParList] ")" Block "end"

ParList ::= NameList [ "," "..." ] | "..."

TableConstructor ::= "{" [ FieldList ] "}"

FieldList ::= Field { FieldSep Field } [ FieldSep ]

Field ::= "[" Exp "]" "=" Exp | ident "=" Exp | Exp

FieldSep ::= "," | ";"

BinOp ::=  "+" | "-" | "*" | "/" | "//" | "^" | "%" | 
     "&" | "~" | "|" | ">>" | "<<" | ".." | 
     "<" | "<=" | ">" | ">=" | "==" | "~=" | 
     "and" | "or"

UnOp ::= "-" | "not" | "#" | "~"